const detailList = [
  // 향수계열 (PERFUME)
  { brand: "Maison Margiela", name: "메종 마르지엘라 레플리카 레이지 선데이 모닝 오 드 뚜왈렛", price: 98000, rating: 4.89, image: "./img/product-list/rank-s/perfume/lst1-maisonmargiela-replica-lazy-sundaymorning.jpg", category: "PERFUME", tags: { scent: "플로랄", mood: "편안함",     lasting: "가볍고 은은하게" }, capacity: ["10ml","30ml","100ml"] },
  { brand: "Diptyque",        name: "딥티크 오르페옹 오 드 퍼퓸",                         price: 269000, rating: 4.75, image: "./img/product-list/rank-s/perfume/lst2-diptyque-ambre-eau-de-parfum.jpg",            category: "PERFUME", tags: { scent: "우디",   mood: "자신감있는", lasting: "오래가고 진하게" }, capacity: ["75ml"] },
  { brand: "Lanvin",          name: "랑방 에끌라 드 아르페쥬 오 드 퍼퓸",                  price: 64000,  rating: 4.58, image: "./img/product-list/rank-s/perfume/lst3-lanvin-eclat-darpege-eau-de-parfum.jpg",     category: "PERFUME", tags: { scent: "플로랄", mood: "로맨틱한",   lasting: "가볍고 은은하게" }, capacity: ["30ml","50ml","100ml"] },
  { brand: "Jennifer Lopez",  name: "제니퍼로페즈 글로우 바이제이로 EDT",                 price: 55000,  rating: 4.56, image: "./img/product-list/rank-s/perfume/lst4-jenniferlopez-glow-by-jlo-edt.jpg",          category: "PERFUME", tags: { scent: "프레시", mood: "에너제틱한", lasting: "가볍고 은은하게" }, capacity: ["30ml","50ml","100ml"] },
  { brand: "Santa Maria Novella", name: "산타 마리아 노벨라 피렌체 1221 에디션 오 드 코롱", price: 145000, rating: 4.48, image: "./img/product-list/rank-s/perfume/lst5-santamarianovella-pfirenze1221-edt.jpg",  category: "PERFUME", tags: { scent: "오리엔탈", mood: "자신감있는", lasting: "오래가고 진하게" }, capacity: ["100ml"] },
  { brand: "Daniel's Truth",  name: "다니엘 트루스 오일 퍼퓸 밤쉘",                        price: 54000,  rating: 4.44, image: "./img/product-list/rank-s/perfume/lst6-danielstruth-oil-perfume-babel.jpg",        category: "PERFUME", tags: { scent: "우디",   mood: "편안함",     lasting: "오래가고 진하게" }, capacity: ["10ml"] },
  { brand: "Diptyque",        name: "딥티크 플레르 드 뽀 오 드 퍼퓸",                      price: 269000, rating: 4.38, image: "./img/product-list/rank-s/perfume/lst7-diptyque-fleur-depeau-eau-de-parfum.jpg",     category: "PERFUME", tags: { scent: "기타",   mood: "편안함",     lasting: "가볍고 은은하게" }, capacity: ["75ml"] }, // 머스크→기타
  { brand: "Jo Malone",       name: "조 말론 블랙베리 앤 베이 코롱",                       price: 110000, rating: 4.32, image: "./img/product-list/rank-s/perfume/lst8-jomalone-blackberry-and-bay-cologne.jpg",    category: "PERFUME", tags: { scent: "프레시", mood: "에너제틱한", lasting: "가볍고 은은하게" }, capacity: ["30ml","100ml"] }, // 프루티→프레시
  { brand: "Clean",           name: "클린 웜 코튼 EDP",                                    price: 57000,  rating: 4.22, image: "./img/product-list/rank-s/perfume/lst9-clean-warm-cotton-edp.jpg",                 category: "PERFUME", tags: { scent: "프레시", mood: "편안함",     lasting: "가볍고 은은하게" }, capacity: ["60ml","100ml"] },
  { brand: "Byredo",          name: "바이레도 블랑쉬 오 드 퍼퓸",                          price: 280000, rating: 4.16, image: "./img/product-list/rank-s/perfume/lst10-byredo-blanche-eau-de-parfum.jpg",          category: "PERFUME", tags: { scent: "플로랄", mood: "편안함",     lasting: "가볍고 은은하게" }, capacity: ["50ml","100ml"] }, // 미니멀한→편안함
  { brand: "Le Labo",         name: "르라보 상탈 33 오 드 퍼퓸",                           price: 225000, rating: 4.88, image: "./img/product-list/rank-s/perfume/lst11-lelabo-santal33.jpg",                      category: "PERFUME", tags: { scent: "우디",   mood: "자신감있는", lasting: "오래가고 진하게" }, capacity: ["50ml","100ml"] },
  { brand: "Le Labo",         name: "르라보 어나더 13 오 드 퍼퓸",                         price: 253000, rating: 4.85, image: "./img/product-list/rank-s/perfume/lst12-lelabo-another13.jpg",                     category: "PERFUME", tags: { scent: "기타",   mood: "편안함",     lasting: "오래가고 진하게" }, capacity: ["50ml","100ml"] }, // 머스크→기타
  { brand: "Creed",           name: "크리드 어벤투스 오 드 퍼퓸",                          price: 384000, rating: 4.83, image: "./img/product-list/rank-s/perfume/lst13-creed-aventus.jpg",                       category: "PERFUME", tags: { scent: "우디",   mood: "자신감있는", lasting: "오래가고 진하게" }, capacity: ["50ml","100ml","250ml","500ml"] }, // 시프레/프루티 성향→우디
  { brand: "Byredo",          name: "바이레도 집시 워터 오 드 퍼퓸",                       price: 180000, rating: 4.78, image: "./img/product-list/rank-s/perfume/lst14-byredo-gypsywater.jpg",                   category: "PERFUME", tags: { scent: "우디",   mood: "신비로운",   lasting: "가볍고 은은하게" }, capacity: ["50ml","100ml"] }, // 아로마틱→우디
  { brand: "Tom Ford",        name: "톰 포드 오드 우드 오 드 퍼퓸",                        price: 323000, rating: 4.77, image: "./img/product-list/rank-s/perfume/lst15-tomford-oudwood.jpg",                     category: "PERFUME", tags: { scent: "오리엔탈", mood: "자신감있는", lasting: "오래가고 진하게" }, capacity: ["50ml","100ml"] },
  { brand: "Byredo",          name: "바이레도 모하비 고스트 오 드 퍼퓸",                   price: 185000, rating: 4.75, image: "./img/product-list/rank-s/perfume/lst16-byredo-mojaveghost.jpg",                  category: "PERFUME", tags: { scent: "플로랄", mood: "자신감있는", lasting: "가볍고 은은하게" }, capacity: ["50ml","100ml"] },
  { brand: "Byredo",          name: "바이레도 발 다프리크 오 드 퍼퓸",                     price: 175000, rating: 4.73, image: "./img/product-list/rank-s/perfume/lst17-byredo-baldafrique.jpg",                  category: "PERFUME", tags: { scent: "프레시", mood: "에너제틱한", lasting: "가볍고 은은하게" }, capacity: ["50ml","100ml"] }, // 시트러스→프레시
  { brand: "Dior",            name: "디올 소바쥬 오 드 뚜왈렛",                            price: 114000, rating: 4.71, image: "./img/product-list/rank-s/perfume/lst18-dior-sauvage.jpg",                        category: "PERFUME", tags: { scent: "프레시", mood: "에너제틱한", lasting: "오래가고 진하게" }, capacity: ["60ml","100ml","200ml","300ml"] }, // 스파이시→프레시
  { brand: "Tom Ford",        name: "톰 포드 블랙 오키드 오 드 퍼퓸",                       price: 168000, rating: 4.66, image: "./img/product-list/rank-s/perfume/lst19-tomford-blackorchid.jpg",                 category: "PERFUME", tags: { scent: "오리엔탈", mood: "신비로운",   lasting: "오래가고 진하게" }, capacity: ["30ml","50ml","100ml"] },
  { brand: "Kilian",          name: "킬리안 엔젤스 셰어",                                  price: 232000, rating: 4.64, image: "./img/product-list/rank-s/perfume/lst20-kilian-angelsshare.jpg",                   category: "PERFUME", tags: { scent: "오리엔탈", mood: "로맨틱한",   lasting: "오래가고 진하게" }, capacity: ["50ml"] },

  // 바디계열 (BODY)
  { brand: "Le Labo", name: "르라보 어나더 13 퍼퓨밍 바디 로션",     price: 92000, rating: 4.83, image: "./img/product-list/rank-s/body/lst1-lelabo-bodylotion-another13.jpg",       category: "BODY", tags: { scent: "기타",   mood: "편안함",     lasting: "가볍고 은은하게" }, capacity: ["250ml"] }, // 머스크→기타
  { brand: "Byredo",  name: "바이레도 모하비 고스트 핸드 크림",       price: 50000, rating: 4.76, image: "./img/product-list/rank-s/body/lst2-byredo-handcream-mojaveghost.jpg",       category: "BODY", tags: { scent: "플로랄", mood: "자신감있는", lasting: "가볍고 은은하게" }, capacity: ["30ml"] },
  { brand: "Byredo",  name: "바이레도 블랑쉬 핸드 크림",             price: 40000, rating: 4.74, image: "./img/product-list/rank-s/body/lst3-byredo-handcream-blanche.jpg",           category: "BODY", tags: { scent: "플로랄", mood: "편안함",     lasting: "가볍고 은은하게" }, capacity: ["30ml"] },
  { brand: "Aesop",   name: "이솝 레저렉션 아로마틱 핸드 밤",        price: 36000, rating: 4.69, image: "./img/product-list/rank-s/body/lst4-aesop-resurrection-handbalm.jpg",         category: "BODY", tags: { scent: "프레시", mood: "편안함",     lasting: "가볍고 은은하게" }, capacity: ["75ml"] },
  { brand: "Byredo",  name: "바이레도 발 다프리크 바디 로션",        price: 80000, rating: 4.69, image: "./img/product-list/rank-s/body/lst5-byredo-bodylotion-baldaffrique.jpg",    category: "BODY", tags: { scent: "프레시", mood: "에너제틱한", lasting: "가볍고 은은하게" }, capacity: ["225ml"] }, // 시트러스→프레시
  { brand: "Diptyque",name: "딥티크 핸드 & 바디 로션 플레르 드 뽀", price: 84000, rating: 4.68, image: "./img/product-list/rank-s/body/lst6-diptyque-bodylotion-fleurdepeau.jpg",       category: "BODY", tags: { scent: "기타",   mood: "편안함",     lasting: "가볍고 은은하게" }, capacity: ["200ml"] }, // 머스크→기타
  { brand: "Dior",    name: "디올 뉴 디올 르 밤 핸드 크림",          price: 67000, rating: 4.67, image: "./img/product-list/rank-s/body/lst7-dior-handcream-lebaume.jpg",               category: "BODY", tags: { scent: "프레시", mood: "편안함",     lasting: "가볍고 은은하게" }, capacity: ["50ml"] },
  { brand: "Aesop",   name: "이솝 레저렉션 아로마틱 핸드 워시",      price: 47000, rating: 4.67, image: "./img/product-list/rank-s/body/lst8-aesop-resurrection-handwash.jpg",         category: "BODY", tags: { scent: "프레시", mood: "에너제틱한", lasting: "가볍고 은은하게" }, capacity: ["500ml"] }, // 상쾌한→에너제틱한
  { brand: "Le Labo", name: "르라보 핸드 포마드 히노키",             price: 38000, rating: 4.63, image: "./img/product-list/rank-s/body/lst9-lelabo-handpomade-hinoki.jpg",            category: "BODY", tags: { scent: "우디",   mood: "편안함",     lasting: "가볍고 은은하게" }, capacity: ["55ml"] },
  { brand: "Diptyque",name: "딥티크 퍼퓸 핸드 크림 도 손",           price: 65000, rating: 4.63, image: "./img/product-list/rank-s/body/lst10-diptyque-handcream-doson.jpg",           category: "BODY", tags: { scent: "플로랄", mood: "로맨틱한",   lasting: "가볍고 은은하게" }, capacity: ["45ml"] },

  // 헤어계열 (HAIR)
  { brand: "Dior",         name: "디올 미스 디올 블루밍 부케 헤어 미스트", price: 66000, rating: 4.75, image: "./img/product-list/rank-s/hair/lst11-dior-hairmist-missdior-bloomingbouquet.jpg", category: "HAIR", tags: { scent: "플로랄",  mood: "로맨틱한",   lasting: "가볍고 은은하게" }, capacity: ["30ml"] }, // 낭만적인→로맨틱한
  { brand: "Chanel",       name: "샤넬 코코 마드모아젤 헤어 미스트",       price: 82000, rating: 4.74, image: "./img/product-list/rank-s/hair/lst12-chanel-hair-cocomademoiselle.jpg",      category: "HAIR", tags: { scent: "오리엔탈", mood: "자신감있는", lasting: "가볍고 은은하게" }, capacity: ["35ml"] }, // 우디-플로럴→오리엔탈(시프레/패출리 뉘앙스)
  { brand: "Diptyque",     name: "딥티크 헤어 미스트 플레르 드 뽀",        price: 80000, rating: 4.73, image: "./img/product-list/rank-s/hair/lst13-diptyque-hairmist-fleurdepeau.jpg",       category: "HAIR", tags: { scent: "기타",    mood: "편안함",     lasting: "가볍고 은은하게" }, capacity: ["30ml"] }, // 머스크→기타
  { brand: "Byredo",       name: "바이레도 블랑쉬 헤어 퍼퓸",               price: 62000, rating: 4.72, image: "./img/product-list/rank-s/hair/lst14-byredo-hair-blanche.jpg",                 category: "HAIR", tags: { scent: "플로랄",  mood: "편안함",     lasting: "가볍고 은은하게" }, capacity: ["75ml"] }, // 클린한→편안함
  { brand: "Diptyque",     name: "딥티크 헤어 미스트 오 로즈",             price: 80000, rating: 4.71, image: "./img/product-list/rank-s/hair/lst15-diptyque-hairmist-eaurose.jpg",           category: "HAIR", tags: { scent: "플로랄",  mood: "로맨틱한",   lasting: "가볍고 은은하게" }, capacity: ["30ml"] }, // 로즈 플로럴→플로랄
  { brand: "Chanel",       name: "샤넬 가브리엘 샤넬 헤어 미스트",         price: 80000, rating: 4.70, image: "./img/product-list/rank-s/hair/lst16-chanel-hair-gabrielle.jpg",               category: "HAIR", tags: { scent: "플로랄",  mood: "자신감있는", lasting: "가볍고 은은하게" }, capacity: ["35ml"] },
  { brand: "Diptyque",     name: "딥티크 헤어 미스트 로 파피에",           price: 84000, rating: 4.68, image: "./img/product-list/rank-s/hair/lst17-diptyque-hairmist-lopapier.jpg",          category: "HAIR", tags: { scent: "우디",    mood: "신비로운",   lasting: "가볍고 은은하게" }, capacity: ["30ml"] }, // 허벌-우디→우디, 자유로운→신비로운
  { brand: "Saint Laurent",name: "입생로랑 리브르 헤어 미스트",            price: 55000, rating: 4.66, image: "./img/product-list/rank-s/hair/lst18-ysl-hairmist-libre.jpg",                   category: "HAIR", tags: { scent: "오리엔탈", mood: "자신감있는", lasting: "가볍고 은은하게" }, capacity: ["30ml"] },
  { brand: "Saint Laurent",name: "입생로랑 몽 파리 헤어 미스트",           price: 58000, rating: 4.64, image: "./img/product-list/rank-s/hair/lst19-ysl-hairmist-monparis.jpg",               category: "HAIR", tags: { scent: "플로랄",  mood: "로맨틱한",   lasting: "가볍고 은은하게" }, capacity: ["30ml"] }, // 플로럴-베리→플로랄
  { brand: "Diptyque",     name: "딥티크 헤어 미스트 오 데 썽",            price: 74000, rating: 4.62, image: "./img/product-list/rank-s/hair/lst20-diptyque-hairmist-eaudessens.jpg",        category: "HAIR", tags: { scent: "우디",    mood: "자신감있는", lasting: "가볍고 은은하게" }, capacity: ["30ml"] },  // 시프레-우디→우디

  // 룸 스프레이/디퓨저/카 디퓨저(세트) 등 '향' 제품 → 태그 부여
  { brand: "Diptyque", name: "딥티크 베이 룸 스프레이", price: 81000, rating: 4.71, image: "./img/product-list/rank-s/etc/lst21-diptyque-roomspray-baies.jpg", category: "ETC", tags: { scent: "프레시", mood: "로맨틱한", lasting: "가볍고 은은하게" }, capacity: ["150ml"] },
  { brand: "Acqua Di Parma", name: "아쿠아 디 파르마 차량용 디퓨저 레더 케이스 다크 그레이", price: 250000, rating: 4.72, image: "./img/product-list/rank-s/etc/lst22-acquadiparma-cardiffuser-darkgrey.jpg", category: "ETC" },
  { brand: "Jo Malone", name: "조 말론 우드 세이지 앤 씨 솔트 리미티드 디퓨저", price: 119000, rating: 4.70, image: "./img/product-list/rank-s/etc/lst23-jomalone-diffuser-woodsage-limited.jpg", category: "ETC", tags: { scent: "프레시", mood: "편안함", lasting: "오래가고 진하게" }, capacity: ["165ml"] },
  { brand: "Diptyque", name: "딥티크 차량용 디퓨저 케이스 & 리필 세트 로즈", price: 153000, rating: 4.73, image: "./img/product-list/rank-s/etc/lst24-diptyque-cardiffuser-rose.jpg", category: "ETC", tags: { scent: "플로랄", mood: "로맨틱한", lasting: "오래가고 진하게" }, capacity: ["Diffuser x1","Capsule 1ea (~3months)"] },
  { brand: "Acqua Di Parma", name: "아쿠아 디 파르마 차량용 디퓨저 레더 케이스 로얄 블루", price: 449000, rating: 4.78, image: "./img/product-list/rank-s/etc/lst25-acquadiparma-cardiffuser-royalblue.jpg", category: "ETC" },
  { brand: "Jo Malone", name: "조 말론 라임 바질 앤 만다린 센트 서라운드 디퓨저", price: 130000, rating: 4.69, image: "./img/product-list/rank-s/etc/lst26-jomalone-diffuser-limebasil.jpg", category: "ETC", tags: { scent: "프레시", mood: "에너제틱한", lasting: "오래가고 진하게" }, capacity: ["165ml"] },
  { brand: "Diptyque", name: "딥티크 차량용 디퓨저 케이스 & 리필 세트 34번가 생제르망", price: 146000, rating: 4.71, image: "./img/product-list/rank-s/etc/lst27-diptyque-cardiffuser-34boulevard.jpg", category: "ETC", tags: { scent: "우디", mood: "신비로운", lasting: "오래가고 진하게" }, capacity: ["Diffuser x1","Capsule 1ea (~3months)"] },
  { brand: "Acqua Di Parma", name: "아쿠아 디 파르마 차량용 디퓨저 레더 케이스 옐로우", price: 151000, rating: 4.75, image: "./img/product-list/rank-s/etc/lst28-acquadiparma-cardiffuser-yellow.jpg", category: "ETC" },
  { brand: "Diptyque", name: "딥티크 로즈 룸 스프레이", price: 127000, rating: 4.74, image: "./img/product-list/rank-s/etc/lst29-diptyque-roomspray-rose.jpg", category: "ETC", tags: { scent: "플로랄", mood: "로맨틱한", lasting: "가볍고 은은하게" }, capacity: ["150ml"] },
  { brand: "Acqua Di Parma", name: "아쿠아 디 파르마 차량용 디퓨저 레더 케이스 레드", price: 396000, rating: 4.77, image: "./img/product-list/rank-s/etc/lst30-acquadiparma-cardiffuser-red.jpg", category: "ETC" },

  // new PERFUME (향수) → 태그
  { brand: "Tamburins", name: "탬버린즈 퍼퓸 리미티드 퍼피", price: 250000, image: "./img/product-list/new/inscent-tamburins-limited-puppy_M-01.jpg", category: "PERFUME", tags: { scent: "오리엔탈", mood: "자신감있는", lasting: "오래가고 진하게" }, capacity: ["11ml","45ml","50ml"] },
  { brand: "Tamburins", name: "탬버린즈 퍼퓸 리미티드 선샤인", price: 250000, image: "./img/product-list/new/inscent-tamburins-limited-sunshine_M-02.jpg", category: "PERFUME", tags: { scent: "프레시", mood: "에너제틱한", lasting: "가볍고 은은하게" }, capacity: ["11ml","45ml","50ml"] },
  { brand: "Byredo",    name: "바이레도 알토 아스트랄 오 드 퍼퓸", price: 355000, image: "./img/product-list/new/inscent-byredo-astral-oud_M.jpg", category: "PERFUME", tags: { scent: "오리엔탈", mood: "자신감있는", lasting: "오래가고 진하게" }, capacity: ["50ml","100ml"] },
  { brand: "Yves Saint",name: "입생로랑 베이비캣 오 드 빠르펭",   price: 360000, image: "./img/product-list/new/inscent-yves-saint-laurent-babycat_M-04.jpg", category: "PERFUME", tags: { scent: "오리엔탈", mood: "자신감있는", lasting: "오래가고 진하게" }, capacity: ["75ml"] },
  { brand: "Diptyque",  name: "딥티크 플레르 드 뽀 오 드 뚜왈렛", price: 196000, image: "./img/product-list/new/inscent-diptyque-fleur-de-peau_M.jpg", category: "PERFUME", tags: { scent: "기타", mood: "편안함", lasting: "가볍고 은은하게" }, capacity: ["50ml","100ml"] },
  { brand: "Le Labo",   name: "르라보 오스만투스 19",             price: 73000,  image: "./img/product-list/new/inscent-le-labo-osmanthus19_M-06.jpg", category: "PERFUME", tags: { scent: "플로랄", mood: "로맨틱한", lasting: "가볍고 은은하게" }, capacity: ["50ml","100ml"] },

  // new BODY (향 보조 제품) → 태그
  { brand: "Byredo", name: "바이레도 유자 트리 핸드 로션",                     price: 91000, image: "./img/product-list/new/01body-byredo-yuzu-tree-hand-lotion.jpg", category: "BODY", tags: { scent: "프레시", mood: "에너제틱한", lasting: "가볍고 은은하게" }, capacity: ["450ml"] },
  { brand: "Acqua Di Parma", name: "아쿠아 디 파르마 핸드 앤 바디 로션 부옹조르노", price: 129000, image: "./img/product-list/new/02body-acquadiparma-buongiorno-hand-body-lotion.jpg", category: "BODY", tags: { scent: "프레시", mood: "에너제틱한", lasting: "가볍고 은은하게" }, capacity: ["300ml"] },
  { brand: "Jo Malone", name: "조말론 라임 바질 앤 만다린 바디 앤 핸드 로션",      price: 59000, image: "./img/product-list/new/03body-jomalone-lime-basil-mandarin-body-hand-lotion.jpg", category: "BODY", tags: { scent: "프레시", mood: "에너제틱한", lasting: "가볍고 은은하게" }, capacity: ["100ml","250ml"] },
  { brand: "Diptyque", name: "딥디크 프레쉬 로션 포 더 바디",                     price: 126000, image: "./img/product-list/new/04body-diptyque-fresh-lotion-body.jpg", category: "BODY", tags: { scent: "프레시", mood: "편안함", lasting: "가볍고 은은하게" }, capacity: ["200ml"] },
  { brand: "Diptyque", name: "딥디크 플레르 드 포 핸드 앤 바디 로션",               price: 91000, image: "./img/product-list/new/05body-diptyque-fleur-de-peau-hand-body-lotion.jpg", category: "BODY", tags: { scent: "기타", mood: "편안함", lasting: "가볍고 은은하게" }, capacity: ["200ml"] },
  { brand: "Tamburins", name: "탬버린즈 샤워리 바디 로션 포그",                    price: 39000, image: "./img/product-list/new/06body-tamburins-showery-fog.jpg", category: "BODY", tags: { scent: "프레시", mood: "편안함", lasting: "가볍고 은은하게" }, capacity: ["235ml"] },
  { brand: "Tamburins", name: "탬버린즈 샤워리 바디 로션 님버스",                  price: 39000, image: "./img/product-list/new/07body-tamburins-showery-nimbus.jpg", category: "BODY", tags: { scent: "프레시", mood: "에너제틱한", lasting: "가볍고 은은하게" }, capacity: ["235ml"] },
];
